Update flow1.yml

diff --git a/.github/workflows/flow1.yml b/.github/workflows/flow1.yml
--- a/.github/workflows/flow1.yml
+++ b/.github/workflows/flow1.yml
@@ -17,6 +17,10 @@ jobs:
     steps:
       - name: Check out current repository
         uses: actions/checkout@v2
+      - name: Change to organization directory
+        run: |
+          ORG_NAME="anvesh898" # Replace with your organization name
+          cd "$ORG_NAME" || { echo "Error changing to organization directory" ; exit 1; }
       - name: Create release branch in each repository
         run: |
           # Set variables
@@ -27,13 +31,30 @@ jobs:
           
           # Check out the develop branch in each repository
           for REPO_NAME in ${REPO_NAMES}; do
-            cd "$REPO_NAME"
+            # Check if repository directory exists
+            if [ ! -d "$REPO_NAME" ]; then
+              echo "Repository directory does not exist: $REPO_NAME"
+              exit 1
+            fi
+            
+            # Change to repository directory
+            cd "$REPO_NAME" || { echo "Error changing to repository directory" ; exit 1; }
+            
+            # Fetch updates from remote repository
             git fetch || { echo "Error fetching updates from remote repository" ; exit 1; }
+            
+            # Check out develop branch
             git checkout develop || { echo "Error checking out develop branch" ; exit 1; }
+            
+            # Update develop branch
             git pull origin develop || { echo "Error updating develop branch" ; exit 1; }
             
             # Create a new branch from develop
             git branch "${RELEASE_NAME}" || { echo "Error creating release branch" ; exit 1; }
+            
+            # Push release branch to remote repository
             git push --set-upstream origin "${RELEASE_NAME}" || { echo "Error pushing release branch to remote repository" ; exit 1; }
+            
+            # Change back to organization directory
             cd ..
           done
