Update flow1.yml

diff --git a/.github/workflows/flow1.yml b/.github/workflows/flow1.yml
--- a/.github/workflows/flow1.yml
+++ b/.github/workflows/flow1.yml
@@ -17,7 +17,7 @@ jobs:
       - name: Change to organization directory
         run: |
           ORG_NAME="anvesh898" # Replace with your organization name
-         # cd "$ORG_NAME" || { echo "Error changing to organization directory" ; exit 1; }
+          cd "$ORG_NAME" || { echo "Error changing to organization directory" ; exit 1; }
       - name: Create release branch in each repository
         run: |
           # Set variables
